/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainApp.java
 *
 * Created on Aug 13, 2011, 7:56:57 PM
 */
package SensorNetwork;

import javax.swing.JOptionPane;

/**
 *
 * @author Saheb
 */
public class mainApp extends javax.swing.JFrame {

    /** Creates new form mainApp */
    public mainApp() {
        initComponents();
        Utility.SetFramePosition(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel_Top = new javax.swing.JPanel();
        jRadioButton_InputText = new javax.swing.JRadioButton();
        jRadioButton_InputFromFile = new javax.swing.JRadioButton();
        jPanel_Bottom = new javax.swing.JPanel();
        cmdSubmit = new javax.swing.JButton();
        cmdLoad = new javax.swing.JButton();
        jPanel_InputText = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_NumNodes = new javax.swing.JTextField();
        jTextField_Range = new javax.swing.JTextField();

        buttonGroup.add(jRadioButton_InputFromFile);
        buttonGroup.add(jRadioButton_InputText);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SensorNetwork");
        setName("SensorNetwork"); // NOI18N

        jPanel_Top.setBackground(new java.awt.Color(0, 0, 102));
        jPanel_Top.setForeground(new java.awt.Color(255, 255, 0));

        jRadioButton_InputText.setText("Input Text");
        jRadioButton_InputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InputTextActionPerformed(evt);
            }
        });

        jRadioButton_InputFromFile.setText("Load Data from File");
        jRadioButton_InputFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InputFromFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TopLayout = new javax.swing.GroupLayout(jPanel_Top);
        jPanel_Top.setLayout(jPanel_TopLayout);
        jPanel_TopLayout.setHorizontalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TopLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jRadioButton_InputText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jRadioButton_InputFromFile)
                .addGap(163, 163, 163))
        );
        jPanel_TopLayout.setVerticalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_InputText)
                    .addComponent(jRadioButton_InputFromFile))
                .addContainerGap())
        );

        jPanel_Bottom.setBackground(new java.awt.Color(0, 0, 102));
        jPanel_Bottom.setForeground(new java.awt.Color(255, 255, 0));

        cmdSubmit.setText("Submit");
        cmdSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSubmitActionPerformed(evt);
            }
        });

        cmdLoad.setText("Load");
        cmdLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BottomLayout = new javax.swing.GroupLayout(jPanel_Bottom);
        jPanel_Bottom.setLayout(jPanel_BottomLayout);
        jPanel_BottomLayout.setHorizontalGroup(
            jPanel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BottomLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(cmdSubmit)
                .addGap(108, 108, 108)
                .addComponent(cmdLoad)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel_BottomLayout.setVerticalGroup(
            jPanel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BottomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdLoad)
                    .addComponent(cmdSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Number of Nodes");

        jLabel2.setText("Range of Nodes");

        jTextField_NumNodes.setText("10");
        jTextField_NumNodes.setEnabled(false);

        jTextField_Range.setText("100");
        jTextField_Range.setEnabled(false);

        javax.swing.GroupLayout jPanel_InputTextLayout = new javax.swing.GroupLayout(jPanel_InputText);
        jPanel_InputText.setLayout(jPanel_InputTextLayout);
        jPanel_InputTextLayout.setHorizontalGroup(
            jPanel_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InputTextLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(69, 69, 69)
                .addGroup(jPanel_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_Range)
                    .addComponent(jTextField_NumNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel_InputTextLayout.setVerticalGroup(
            jPanel_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InputTextLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_NumNodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel_InputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(jPanel_Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel_InputText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(135, 135, 135)
                .addComponent(jPanel_Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_InputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InputTextActionPerformed
        // TODO add your handling code here:
        SetEnableInput(true);
        cmdLoad.setEnabled(false);
        cmdSubmit.setEnabled(true);
    }//GEN-LAST:event_jRadioButton_InputTextActionPerformed

    private void cmdSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSubmitActionPerformed
        // TODO add your handling code here:
        // Validate Text Input
        if (jTextField_NumNodes.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Number of Nodes", null, WIDTH);
            return;
        }
        if (!Utility.isNum(jTextField_NumNodes.getText())) {
            JOptionPane.showMessageDialog(this, "Input is Not a Number", null, WIDTH);
            return;
        }
        if (jTextField_Range.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Number of Nodes", null, WIDTH);
            return;
        }
        if (!Utility.isNum(jTextField_Range.getText())) {
            JOptionPane.showMessageDialog(this, "Input is Not a Number", null, WIDTH);
            return;
        }

        Utility.GenerateNodes(Integer.parseInt(jTextField_NumNodes.getText()),
                Integer.parseInt(jTextField_Range.getText()),
                Globals.sWidth,
                Globals.sHeight);

        // Generate Edges
        Utility.CalculateEdges();

        // Graphics Preview in Frame
        new GraphicsPreview().show();
    }//GEN-LAST:event_cmdSubmitActionPerformed

    private void jRadioButton_InputFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InputFromFileActionPerformed
        // TODO add your handling code here:
        SetEnableInput(false);
        cmdLoad.setEnabled(true);
        cmdSubmit.setEnabled(false);
    }//GEN-LAST:event_jRadioButton_InputFromFileActionPerformed

    private void cmdLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoadActionPerformed
        // TODO add your handling code here:

        Utility.LoadData(this);
        // Generate Edges
        Utility.CalculateEdges();

        // Graphics Preview in Frame
        new GraphicsPreview().show();
    }//GEN-LAST:event_cmdLoadActionPerformed

    private void SetEnableInput(boolean val) {
        jTextField_NumNodes.setEnabled(val);
        jTextField_Range.setEnabled(val);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cmdLoad;
    private javax.swing.JButton cmdSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_Bottom;
    private javax.swing.JPanel jPanel_InputText;
    private javax.swing.JPanel jPanel_Top;
    private javax.swing.JRadioButton jRadioButton_InputFromFile;
    private javax.swing.JRadioButton jRadioButton_InputText;
    private javax.swing.JTextField jTextField_NumNodes;
    private javax.swing.JTextField jTextField_Range;
    // End of variables declaration//GEN-END:variables
}
